import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import type { RuntimeMode } from "@synara/contracts";
import { Effect, Layer, Scope, ServiceMap } from "effect";
import { ChildProcessSpawner } from "effect/unstable/process";

import { buildProviderChildEnvironment } from "../../providerChildEnvironment.ts";
import * as AcpErrors from "./AcpErrors.ts";
import {
  AcpSessionRuntime,
  type AcpSessionRuntimeOptions,
  type AcpSessionRuntimeShape,
  type AcpSpawnInput,
} from "./AcpSessionRuntime.ts";

export interface DeepSeekAcpRuntimeSettings {
  readonly binaryPath?: string;
  readonly configPath?: string;
  readonly model?: string;
}

export interface DeepSeekAcpRuntimeInput extends Omit<
  AcpSessionRuntimeOptions,
  "authMethodId" | "freshSessionRetry" | "resolveAuthMethodId" | "spawn"
> {
  readonly childProcessSpawner: ChildProcessSpawner.ChildProcessSpawner["Service"];
  readonly settings: DeepSeekAcpRuntimeSettings | null | undefined;
  readonly runtimeMode: RuntimeMode;
}

const DEFAULT_DEEPSEEK_MODEL = "deepseek-v4-pro";
const KNOWN_DEEPSEEK_MODELS = ["deepseek-v4-flash", "deepseek-v4-pro"] as const;

function yamlQuoted(value: string): string {
  return JSON.stringify(value);
}

export function deepSeekPermissionMode(runtimeMode: RuntimeMode): string {
  return runtimeMode === "full-access" ? "danger-full-access" : "workspace-write";
}

export function buildDeepSeekHarnessConfig(
  modelInput: string | undefined,
  runtimeMode: RuntimeMode,
): string {
  const model = modelInput?.trim() || DEFAULT_DEEPSEEK_MODEL;
  const models = [...new Set([...KNOWN_DEEPSEEK_MODELS, model])];
  const modelRows = models.map((entry) => `      - id: ${yamlQuoted(entry)}`).join("\n");
  const permissionMode = deepSeekPermissionMode(runtimeMode);
  const approvalPolicy = runtimeMode === "full-access" ? "never" : "ask";

  return `# Generated by Synara for the DeepSeek Harness ACP bridge.
# Keep stdout reserved for ACP JSON-RPC; provider diagnostics belong on stderr.
- id: llm-deepseek
  name: '@deepseek-ai/dsh-llm-deepseek'
  config:
    thinking: enabled
    reasoningEffort: max
    models:
${modelRows}

- id: sandbox
  name: '@deepseek-ai/dsh-sandbox-local'

- id: sandbox-policy
  name: '@deepseek-ai/dsh-sandbox-policy'
  config:
    mode: ${permissionMode}
    workspaceRoot: !!js process.cwd()

- id: subprocess
  name: '@deepseek-ai/dsh-subprocess-local'

- id: bash
  name: '@deepseek-ai/dsh-bash-sandbox'
  config:
    timeoutMs: 60000

- id: approval
  name: '@deepseek-ai/dsh-user-approval'
  config:
    policy: ${approvalPolicy}

- id: acp-agent
  name: '@deepseek-ai/dsh-acp-demo'
  config:
    provider: deepseek-official
    model: ${yamlQuoted(model)}
    persistenceRoot: !!js process.env.SYNARA_DEEPSEEK_SESSIONS_ROOT ?? './.synara-deepseek-sessions'
    persistenceCompression: zstd
    workspaceContext:
      maxBytes: 65536
    persona: |
      You are a coding assistant powered by the {{model}} model. Your working directory is {{cwd}}.
      Verify your work by running the code or tests. Keep answers brief and factual.

- id: token-meter
  name: '@deepseek-ai/dsh-token-meter'

- id: compaction-basic
  name: '@deepseek-ai/dsh-compaction-basic'
  config:
    thresholdRatio: 0.8
    retainRatio: 0.08
    maxTokens: 8192
    compactionRetries: 1

- id: fs-sandbox
  name: '@deepseek-ai/dsh-fs-sandbox'
  config:
    cwd: !!js process.cwd()

- id: fs-observation-policy
  name: '@deepseek-ai/dsh-fs-observation-policy'

- id: tool-fs
  name: '@deepseek-ai/dsh-tool-fs'
`;
}

const makeGeneratedConfig = Effect.fnUntraced(function* (
  model: string | undefined,
  runtimeMode: RuntimeMode,
) {
  const scope = yield* Scope.Scope;
  const root = yield* Effect.tryPromise({
    try: () => fs.mkdtemp(path.join(os.tmpdir(), "synara-deepseek-")),
    catch: (cause) =>
      new AcpErrors.AcpTransportError({
        detail: "Unable to create the temporary DeepSeek Harness configuration directory.",
        cause,
      }),
  });
  const configPath = path.join(root, "cordis.yml");
  yield* Effect.tryPromise({
    try: () => fs.writeFile(configPath, buildDeepSeekHarnessConfig(model, runtimeMode), "utf8"),
    catch: (cause) =>
      new AcpErrors.AcpTransportError({
        detail: "Unable to write the temporary DeepSeek Harness configuration.",
        cause,
      }),
  });
  yield* Scope.addFinalizer(
    scope,
    Effect.promise(() => fs.rm(root, { recursive: true, force: true })).pipe(Effect.ignore),
  );
  return configPath;
});

export function buildDeepSeekAcpSpawnInput(input: {
  readonly settings: DeepSeekAcpRuntimeSettings | null | undefined;
  readonly configPath: string;
  readonly generatedSessionsRoot?: string;
  readonly cwd: string;
  readonly runtimeMode: RuntimeMode;
}): AcpSpawnInput {
  const inheritedEnv = buildProviderChildEnvironment({
    provider: "deepseek",
    inheritedSynaraKeys: ["SYNARA_DEEPSEEK_SESSIONS_ROOT"],
  });
  const inheritedSessionsRoot = inheritedEnv.SYNARA_DEEPSEEK_SESSIONS_ROOT?.trim();
  return {
    command: input.settings?.binaryPath?.trim() || "dsh-acp-demo",
    args: ["--config", input.configPath],
    cwd: input.cwd,
    env: {
      ...inheritedEnv,
      ...(input.generatedSessionsRoot && !inheritedSessionsRoot
        ? { SYNARA_DEEPSEEK_SESSIONS_ROOT: input.generatedSessionsRoot }
        : {}),
      DSH_PERMISSION_MODE: deepSeekPermissionMode(input.runtimeMode),
    },
  };
}

export const makeDeepSeekAcpRuntime = (
  input: DeepSeekAcpRuntimeInput,
): Effect.Effect<AcpSessionRuntimeShape, AcpErrors.AcpError, Scope.Scope> =>
  Effect.gen(function* () {
    const customConfigPath = input.settings?.configPath?.trim();
    const configPath =
      customConfigPath || (yield* makeGeneratedConfig(input.settings?.model, input.runtimeMode));
    const acpContext = yield* Layer.build(
      AcpSessionRuntime.layer({
        ...input,
        spawn: buildDeepSeekAcpSpawnInput({
          settings: input.settings,
          configPath,
          ...(customConfigPath
            ? {}
            : { generatedSessionsRoot: path.join(path.dirname(configPath), "sessions") }),
          cwd: input.cwd,
          runtimeMode: input.runtimeMode,
        }),
      }).pipe(
        Layer.provide(
          Layer.succeed(ChildProcessSpawner.ChildProcessSpawner, input.childProcessSpawner),
        ),
      ),
    );
    return ServiceMap.getUnsafe(acpContext, AcpSessionRuntime);
  });
